### ISSUE TITLE
please compiling it and post to release filed for people download it.

### ISSUE THREAD

**Issue by cxj98** [x64dbg/SlothBP#1]
i dont know any programming knowledge, and dont know how to compiling this plugin myself, will you compiling it and post it to release that people can download it, thanks.

**Comment by mrexodia** [comment]
1. Download and install [Visual Studio 2013 Community Edition](https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx)
2. Clone/download the project
3. Open `SlothBP.sln` in Visual Studio 2013
4. Press Build
5. Profit

Also alternatively you could look at the [SlothBP](https://github.com/x64dbg/SlothBP) page and see the download link on top.
