### ISSUE TITLE
It can NOT work on Windows 7 X64

### ISSUE THREAD

**Issue by peter8777555** [x64dbg/SlothBP#5]
Place Plugin in x32/64 plugin directory

C:\Test\x32\plugins

SlothBP.dp32
SlothBP.ini

![z1](https://user-images.githubusercontent.com/29886853/197862291-c4183410-fc8c-4b6f-9437-0429ce76368b.png)

**Comment by mrexodia** [comment]
Check the `Log` tab

**Comment by peter8777555** [comment]
I check log and work.
Thank you.
